const ERROR_CODES = {
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
    AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
    MISSING_REFRESH_TOKEN: 'MISSING_REFRESH_TOKEN',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    MISSING_AUTH_HEADER: 'MISSING_AUTH_HEADER',

    BOOKING_ERROR: 'BOOKING_ERROR',

    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    MISSING_QUERY: 'MISSING_QUERY',
    MISSING_HOTEL_ID: 'MISSING_HOTEL_ID',
    MISSING_REGION: 'MISSING_REGION',

    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SERVER_ERROR: 'SERVER_ERROR'
};

module.exports = ERROR_CODES;
