const ERROR_CODES = {
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
    AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
    MISSING_REFRESH_TOKEN: 'MISSING_REFRESH_TOKEN',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    MISSING_AUTH_HEADER: 'MISSING_AUTH_HEADER',
    MISSING_EMAIL: 'MISSING_EMAIL',
    MISSING_PASSWORD: 'MISSING_PASSWORD',
    PASSWORD_SAME_AS_OLD: 'PASSWORD_SAME_AS_OLD',
    INVALID_TOKEN: 'INVALID_TOKEN',

    RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',

    BOOKING_ERROR: 'BOOKING_ERROR',
    MISSING_PARAMETER: 'MISSING_PARAMETER',
    REVIEW_EXISTS: 'REVIEW_EXISTS',
    INVALID_TYPE: 'INVALID_TYPE',
    MISSING_FILE: 'MISSING_FILE',

    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    MISSING_QUERY: 'MISSING_QUERY',
    MISSING_HOTEL_ID: 'MISSING_HOTEL_ID',
    MISSING_REGION: 'MISSING_REGION',

    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SERVER_ERROR: 'SERVER_ERROR'
};

module.exports = ERROR_CODES;
